### ISSUE TITLE
Currency Converter does not work

### ISSUE THREAD

**Issue by DRYN07** [adirh3/Fluent-Search-Tasks#4]
Maybe I posted this in the wrong place before, sorry for that.

In the past, it worked well but nowadays I noticed that it just shows "Nothing to show". I tried to disable/re-enable it but nothing happened. Am I doing something wrong or is it a bug?

![image](https://github.com/adirh3/Fluent-Search/assets/29770761/7a648307-ef38-463e-92d8-1c063b856cff)

![image](https://github.com/adirh3/Fluent-Search-Tasks/assets/29770761/c1d50e16-21ed-4976-b6e0-8e8d6216a4ca)

**Comment by eikaramba** [comment]
hey there you are right. i fixed it today and pushed a pull request. you can also use the file from the pull request and import it directly to use it immediately https://github.com/adirh3/Fluent-Search-Tasks/pull/5

**Comment by eikaramba** [comment]
can be closed now

**Comment by DRYN07** [comment]
Perfect, thank you!
